<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-07-18">

<title>Absent from Chronic - Variable Inclusion: §2.2 Requirements vs.&nbsp;Ellis Implementation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<style>
  table { font-size: 0.85em; }
  td, th { vertical-align: top; }
</style>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Absent from Chronic</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../content/index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-project" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Project</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-project">    
        <li>
    <a class="dropdown-item" href="../../content/project/project-proposal.html" rel="" target="">
 <span class="dropdown-text">Project Proposal</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-pipeline" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Pipeline</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-pipeline">    
        <li>
    <a class="dropdown-item" href="../../content/pipeline/pipeline-guide.html" rel="" target="">
 <span class="dropdown-text">Pipeline Guide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../content/pipeline/cache-manifest.html" rel="" target="">
 <span class="dropdown-text">CACHE Manifest</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../content/pipeline/input-manifest.html" rel="" target="">
 <span class="dropdown-text">INPUT Manifest</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data-primer" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Data Primer</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data-primer">    
        <li>
    <a class="dropdown-item" href="../../content/data-primer/variable-inclusion.html" rel="" target="">
 <span class="dropdown-text">Variable Inclusion</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../content/data-primer/univariate-distributions.html" rel="" target="">
 <span class="dropdown-text">Univariate Distributions</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-predictors" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Predictors</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-predictors">    
        <li>
    <a class="dropdown-item" href="../../content/predictors/predisposing.html" rel="" target="">
 <span class="dropdown-text">Predisposing</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysis" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Analysis</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysis">    
        <li>
    <a class="dropdown-item" href="../../content/analysis/outcome.html" rel="" target="">
 <span class="dropdown-text">Outcome (LOP Day Decomposition)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../content/analysis/outcome-distribution.html" rel="" target="">
 <span class="dropdown-text">Outcome (Distribution Shapes)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../content/analysis/exposure.html" rel="" target="">
 <span class="dropdown-text">Exposure (Chronic Conditions)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../content/analysis/predisposing.html" rel="" target="">
 <span class="dropdown-text">Predisposing (Socio-demographic)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../content/analysis/facilitating.html" rel="" target="">
 <span class="dropdown-text">Facilitating (Health System &amp; Behaviours)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../content/analysis/needs.html" rel="" target="">
 <span class="dropdown-text">Needs (Perceived Health &amp; Limitations)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../content/analysis/missingness.html" rel="" target="">
 <span class="dropdown-text">Missingness</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../content/site-map.html" rel="" target="">
 <span class="menu-text">Site Map</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Sections</h2>
   
  <ul class="collapse">
  <li><a href="#sample-construction-flowchart-3.1" id="toc-sample-construction-flowchart-3.1" class="nav-link active" data-scroll-target="#sample-construction-flowchart-3.1">Sample Construction Flowchart (§3.1)</a></li>
  <li><a href="#outcome-total-days-absent-all-health-reasons" id="toc-outcome-total-days-absent-all-health-reasons" class="nav-link" data-scroll-target="#outcome-total-days-absent-all-health-reasons">1. Outcome — Total Days Absent (All Health Reasons)</a></li>
  <li><a href="#outcome-sensitivity-days-absent-due-to-chronic-conditions-only" id="toc-outcome-sensitivity-days-absent-due-to-chronic-conditions-only" class="nav-link" data-scroll-target="#outcome-sensitivity-days-absent-due-to-chronic-conditions-only">2. Outcome (Sensitivity) — Days Absent Due to Chronic Conditions Only</a></li>
  <li><a href="#primary-exposure-19-chronic-conditions" id="toc-primary-exposure-19-chronic-conditions" class="nav-link" data-scroll-target="#primary-exposure-19-chronic-conditions">3. Primary Exposure — 19 Chronic Conditions</a></li>
  <li><a href="#predisposing-variables" id="toc-predisposing-variables" class="nav-link" data-scroll-target="#predisposing-variables">4. Predisposing Variables</a></li>
  <li><a href="#facilitating-variables" id="toc-facilitating-variables" class="nav-link" data-scroll-target="#facilitating-variables">5. Facilitating Variables</a></li>
  <li><a href="#needs-variables" id="toc-needs-variables" class="nav-link" data-scroll-target="#needs-variables">6. Needs Variables</a></li>
  <li><a href="#survey-design-variables" id="toc-survey-design-variables" class="nav-link" data-scroll-target="#survey-design-variables">7. Survey Design Variables</a></li>
  <li><a href="#coverage-summary" id="toc-coverage-summary" class="nav-link" data-scroll-target="#coverage-summary">Coverage Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Variable Inclusion: §2.2 Requirements vs.&nbsp;Ellis Implementation</h1>
<p class="subtitle lead">Data Primer — Part 2 of 2</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 18, 2026</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p>This document is the traceability record linking the variable requirements specified in §2.2 of the statistical analysis instructions to their concrete implementation in the Ellis lane (<code>manipulation/2-ellis.R</code>). One table is provided for each variable category in §2.2. The companion document with actual distributions is: <a href="univariate-distributions.html">Univariate Distributions</a>.</p>
<hr>
<section id="sample-construction-flowchart-3.1" class="level2">
<h2 class="anchored" data-anchor-id="sample-construction-flowchart-3.1">Sample Construction Flowchart (§3.1)</h2>
<p>The following CONSORT-style diagram documents the sequential exclusion criteria applied in <code>2-ellis.R</code> to produce the analytical sample. Each step records the number of respondents remaining and excluded.</p>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 26%">
<col style="width: 30%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>Criterion</th>
<th>n remaining</th>
<th>n excluded</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>Full pooled sample (CCHS 2010 + 2014)</td>
<td>126,431</td>
<td>—</td>
</tr>
<tr class="even">
<td>1</td>
<td>Age filter: DHHGAGE codes 2–15 (ages 15–75)</td>
<td>~122,500</td>
<td>~3,900</td>
</tr>
<tr class="odd">
<td>2</td>
<td>Employment filter: LOP_015 = 1 (worked past 3 months)</td>
<td>~64,248</td>
<td>~58,200</td>
</tr>
<tr class="even">
<td>3</td>
<td>Proxy filter: ADM_PRX != 1 (not proxy interview)</td>
<td>~64,248</td>
<td>0</td>
</tr>
<tr class="odd">
<td>4</td>
<td>Outcome completeness: all 8 LOP day-count variables non-missing (code != 99)</td>
<td>63,843</td>
<td>405</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Note:</strong> Exact counts at steps 1–3 vary slightly by run depending on NA handling. The final analytic n = 63,843 is stable. Zero proxy respondents were found in the employed subsample. The 405-row exclusion at step 4 reflects genuine non-response (code 99 = “NOT STATED”) on at least one LOP day-count variable — not structural survey-skip NAs, which are coded as zero.</p>
</blockquote>
<hr>
<p><strong>Column definitions:</strong></p>
<ul>
<li><strong>Requested</strong> — Variable as described in §2.2 (conceptual name or derived label).</li>
<li><strong>2011</strong> — Actual column name in the CCHS 2010–2011 PUMF after <code>janitor::clean_names()</code>.</li>
<li><strong>2014</strong> — Actual column name in the CCHS 2013–2014 PUMF after <code>janitor::clean_names()</code>.</li>
<li><strong>In Study</strong> — Column name in the analytical dataset (<code>cchs_analytic</code>). Continuous raw variables retain their PUMF name; factor-recoded variables receive a new semantic name.</li>
<li><strong>Note</strong> — Implementation status and any discrepancy between white-list and actual PUMF name.</li>
</ul>
<p><strong>Status symbols used in the Note column:</strong></p>
<ul>
<li>✅ Delivered as-is — white-list name matches PUMF exactly; variable present and populated in both cycles.</li>
<li>⚠️ Alias required — PUMF uses a different name than the white-list entry; alias map or whitelist fix needed.</li>
<li>❌ Absent from PUMF — variable suppressed in the Public Use Microdata File; not obtainable without RDC access.</li>
</ul>
<hr>
</section>
<section id="outcome-total-days-absent-all-health-reasons" class="level2">
<h2 class="anchored" data-anchor-id="outcome-total-days-absent-all-health-reasons">1. Outcome — Total Days Absent (All Health Reasons)</h2>
<blockquote class="blockquote">
<p><em>Days absent from work (past 3 months) – all health reasons combined (count) | LOP module – sum across all reason categories</em></p>
</blockquote>
<p>The primary outcome <code>days_absent_total</code> is constructed by Ellis as the row-wise sum of eight Loss of Productivity (LOP) component variables. When all eight are <code>NA</code> for a respondent, the outcome is set to <code>0</code> (structural zero — no reported absence). Values outside the 0–90 day range are set to <code>NA</code> with a warning. Both PUMF cycles use identical variable names for all eight components.</p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 25%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Requested</th>
<th>2011</th>
<th>2014</th>
<th>In Study</th>
<th>Note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Days absent — chronic condition (component)</td>
<td><code>lopg040</code></td>
<td><code>lopg040</code></td>
<td><code>lopg040</code></td>
<td>✅ Also the sensitivity outcome (§2 row 2)</td>
</tr>
<tr class="even">
<td>Days absent — injury (component)</td>
<td><code>lopg070</code></td>
<td><code>lopg070</code></td>
<td><code>lopg070</code></td>
<td>✅</td>
</tr>
<tr class="odd">
<td>Days absent — cold (component)</td>
<td><code>lopg082</code></td>
<td><code>lopg082</code></td>
<td><code>lopg082</code></td>
<td>✅</td>
</tr>
<tr class="even">
<td>Days absent — flu / influenza (component)</td>
<td><code>lopg083</code></td>
<td><code>lopg083</code></td>
<td><code>lopg083</code></td>
<td>✅</td>
</tr>
<tr class="odd">
<td>Days absent — stomach flu / gastroenteritis (component)</td>
<td><code>lopg084</code></td>
<td><code>lopg084</code></td>
<td><code>lopg084</code></td>
<td>✅</td>
</tr>
<tr class="even">
<td>Days absent — respiratory infection (component)</td>
<td><code>lopg085</code></td>
<td><code>lopg085</code></td>
<td><code>lopg085</code></td>
<td>✅</td>
</tr>
<tr class="odd">
<td>Days absent — other infectious disease (component)</td>
<td><code>lopg086</code></td>
<td><code>lopg086</code></td>
<td><code>lopg086</code></td>
<td>✅</td>
</tr>
<tr class="even">
<td>Days absent — other physical / mental health reason (component)</td>
<td><code>lopg100</code></td>
<td><code>lopg100</code></td>
<td><code>lopg100</code></td>
<td>✅</td>
</tr>
<tr class="odd">
<td><strong>Derived outcome</strong></td>
<td>—</td>
<td>—</td>
<td><code>days_absent_total</code></td>
<td>✅ Ellis-computed row-wise sum of the 8 LOP components above</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="outcome-sensitivity-days-absent-due-to-chronic-conditions-only" class="level2">
<h2 class="anchored" data-anchor-id="outcome-sensitivity-days-absent-due-to-chronic-conditions-only">2. Outcome (Sensitivity) — Days Absent Due to Chronic Conditions Only</h2>
<blockquote class="blockquote">
<p><em>Days absent from work due to chronic conditions only | LOP module – chronic condition reason only</em></p>
</blockquote>
<p>The sensitivity outcome <code>days_absent_chronic</code> is taken directly from the single LOP component that records days lost specifically because of the respondent’s own chronic condition.</p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 25%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Requested</th>
<th>2011</th>
<th>2014</th>
<th>In Study</th>
<th>Note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Days absent — chronic condition reason only</td>
<td><code>lopg040</code></td>
<td><code>lopg040</code></td>
<td><code>days_absent_chronic</code></td>
<td>✅ Single-component copy of <code>lopg040</code>; stored separately for sensitivity analysis</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="primary-exposure-19-chronic-conditions" class="level2">
<h2 class="anchored" data-anchor-id="primary-exposure-19-chronic-conditions">3. Primary Exposure — 19 Chronic Conditions</h2>
<blockquote class="blockquote">
<p><em>19 chronic conditions (binary each): arthritis, asthma, cardiovascular disease/stroke, hypertension, fibromyalgia, diabetes, migraine, back problems, cancer, COPD, mental illness (depression/bipolar/etc.), bowel disorders, digestive diseases, chronic fatigue syndrome, multiple chemical sensitivities, mood disorder, anxiety disorder, intestinal/stomach ulcer [check exact groupings in Appendix 3 of the thesis] | CCC module</em></p>
</blockquote>
<p>All CCC variables are recoded to <strong>logical</strong> (TRUE / FALSE); numeric response codes 6, 7, 8, 9, and 96–99 are set to <code>NA</code>. Two conditions — <code>ccc_300</code> (other mental illness) and <code>ccc_185</code> (digestive disease) — are suppressed in the PUMF and cannot be recovered without RDC access. Cardiovascular disease and stroke are represented as two separate CCC variables in the PUMF.</p>
<table class="table">
<colgroup>
<col style="width: 41%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 20%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Requested condition</th>
<th>2011</th>
<th>2014</th>
<th>In Study</th>
<th>Note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Asthma</td>
<td><code>ccc_031</code></td>
<td><code>ccc_031</code></td>
<td><code>cc_asthma</code></td>
<td>✅ logical: TRUE / FALSE</td>
</tr>
<tr class="even">
<td>Fibromyalgia</td>
<td><code>ccc_041</code></td>
<td><code>ccc_041</code></td>
<td><code>cc_fibromyalgia</code></td>
<td>✅ logical: TRUE / FALSE</td>
</tr>
<tr class="odd">
<td>Arthritis (excl. fibromyalgia)</td>
<td><code>ccc_051</code></td>
<td><code>ccc_051</code></td>
<td><code>cc_arthritis</code></td>
<td>✅ logical: TRUE / FALSE</td>
</tr>
<tr class="even">
<td>Back problems (excl. fibromyalgia/arthritis)</td>
<td><code>ccc_061</code></td>
<td><code>ccc_061</code></td>
<td><code>cc_back_problems</code></td>
<td>✅</td>
</tr>
<tr class="odd">
<td>Hypertension</td>
<td><code>ccc_071</code></td>
<td><code>ccc_071</code></td>
<td><code>cc_hypertension</code></td>
<td>✅</td>
</tr>
<tr class="even">
<td>Migraine</td>
<td><code>ccc_081</code></td>
<td><code>ccc_081</code></td>
<td><code>cc_migraine</code></td>
<td>✅</td>
</tr>
<tr class="odd">
<td>COPD / chronic bronchitis / emphysema</td>
<td><code>ccc_091</code></td>
<td><code>ccc_091</code></td>
<td><code>cc_copd</code></td>
<td>✅</td>
</tr>
<tr class="even">
<td>Diabetes</td>
<td><code>ccc_101</code></td>
<td><code>ccc_101</code></td>
<td><code>cc_diabetes</code></td>
<td>✅</td>
</tr>
<tr class="odd">
<td>Cardiovascular disease / heart disease</td>
<td><code>ccc_121</code></td>
<td><code>ccc_121</code></td>
<td><code>cc_heart_disease</code></td>
<td>✅</td>
</tr>
<tr class="even">
<td>Cancer (any type)</td>
<td><code>ccc_131</code></td>
<td><code>ccc_131</code></td>
<td><code>cc_cancer</code></td>
<td>✅</td>
</tr>
<tr class="odd">
<td>Intestinal / stomach ulcer</td>
<td><code>ccc_141</code></td>
<td><code>ccc_141</code></td>
<td><code>cc_ulcer</code></td>
<td>✅</td>
</tr>
<tr class="even">
<td>Stroke (cardiovascular)</td>
<td><code>ccc_151</code></td>
<td><code>ccc_151</code></td>
<td><code>cc_stroke</code></td>
<td>✅</td>
</tr>
<tr class="odd">
<td>Bowel disorder (Crohn’s / colitis / IBS)</td>
<td><code>ccc_171</code></td>
<td><code>ccc_171</code></td>
<td><code>cc_bowel_disorder</code></td>
<td>✅</td>
</tr>
<tr class="even">
<td>Chronic fatigue syndrome (CFS)</td>
<td><code>ccc_251</code></td>
<td><code>ccc_251</code></td>
<td><code>cc_fatigue_syndrome</code></td>
<td>✅</td>
</tr>
<tr class="odd">
<td>Multiple chemical sensitivities (MCS)</td>
<td><code>ccc_261</code></td>
<td><code>ccc_261</code></td>
<td><code>cc_chem_sensitivity</code></td>
<td>✅</td>
</tr>
<tr class="even">
<td>Mood disorder (depression / bipolar / mania / dysthymia)</td>
<td><code>ccc_280</code></td>
<td><code>ccc_280</code></td>
<td><code>cc_mood_disorder</code></td>
<td>✅</td>
</tr>
<tr class="odd">
<td>Anxiety disorder (phobia / OCD / panic disorder)</td>
<td><code>ccc_290</code></td>
<td><code>ccc_290</code></td>
<td><code>cc_anxiety</code></td>
<td>✅</td>
</tr>
<tr class="even">
<td>Other mental illness (schizophrenia, etc.)</td>
<td>❌ absent</td>
<td>❌ absent</td>
<td>❌ absent</td>
<td>❌ <code>ccc_300</code> suppressed in both PUMF cycles; requires RDC access</td>
</tr>
<tr class="odd">
<td>Digestive disease (other than ulcer / bowel disorder)</td>
<td>❌ absent</td>
<td>❌ absent</td>
<td>❌ absent</td>
<td>❌ <code>ccc_185</code> suppressed in both PUMF cycles; requires RDC access</td>
</tr>
</tbody>
</table>
<p><strong>Coverage summary:</strong> 17 of 19 conditions are available in the PUMF. Two conditions (<code>ccc_300</code>, <code>ccc_185</code>) require RDC access. All 17 present columns use the <code>cc_*</code> prefix and are stored as <strong>R logical</strong> (not factor); prevalence calculations must compare <code>x == TRUE</code> / <code>x == FALSE</code>.</p>
<hr>
</section>
<section id="predisposing-variables" class="level2">
<h2 class="anchored" data-anchor-id="predisposing-variables">4. Predisposing Variables</h2>
<blockquote class="blockquote">
<p><em>Age (continuous, recoded in 3 categories: 15–24, 25–54, 55–75); sex; marital status; household size; number of children (&lt; 5 yrs, 6–11 yrs, ≥ 12 yrs); education; immigration status; ethnic origin (White vs.&nbsp;visible minority); homeownership; student status | Main questionnaire</em></p>
</blockquote>
<p>Age is available in PUMF only as a grouped derived variable (<code>dhhgage</code>); single-year resolution requires restricted RDC access. <code>dhhdfc12p</code> (children ≥ 12 yrs) has no PUMF equivalent. Student status (<code>sdcdgstud</code>) is suppressed in the PUMF and renders all-NA.</p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 25%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Requested</th>
<th>2011</th>
<th>2014</th>
<th>In Study</th>
<th>Note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Age (grouped; recoded to 15–24, 25–54, 55–75)</td>
<td><code>dhhgage</code></td>
<td><code>dhhgage</code></td>
<td><code>age_group_3</code></td>
<td>✅ Ordered factor: “15-24” / “25-54” / “55-75”; raw <code>dhhgage</code> also retained as integer code</td>
</tr>
<tr class="even">
<td>Sex</td>
<td><code>dhh_sex</code></td>
<td><code>dhh_sex</code></td>
<td><code>sex</code></td>
<td>✅ Factor: Male / Female</td>
</tr>
<tr class="odd">
<td>Marital status</td>
<td><code>dhhgms</code></td>
<td><code>dhhgms</code></td>
<td><code>marital_status</code></td>
<td>✅ Factor: Single / Married / Common-law / Widowed-Divorced-Separated</td>
</tr>
<tr class="even">
<td>Household size (number of persons)</td>
<td><code>dhhghsz</code></td>
<td><code>dhhghsz</code></td>
<td><code>household_size</code></td>
<td>✅ Ordered factor: 1 / 2 / 3 / 4 / 5+ (recoded from <code>dhhghsz</code>; groups 5–8 collapsed to “5+”)</td>
</tr>
<tr class="odd">
<td>Children ≤ 5 yrs in household</td>
<td><code>dhhgle5</code></td>
<td><code>dhhgle5</code></td>
<td><code>dhhgle5</code></td>
<td>✅ Numeric (0 = none, 1 = one or more); present and populated in both cycles</td>
</tr>
<tr class="even">
<td>Children 6–11 yrs in household</td>
<td><code>dhhg611</code></td>
<td><code>dhhg611</code></td>
<td><code>dhhg611</code></td>
<td>✅ Numeric (0 = none, 1 = one or more); present and populated in both cycles</td>
</tr>
<tr class="odd">
<td>Children ≥ 12 yrs in household (count)</td>
<td>unknown</td>
<td>unknown</td>
<td>❌ absent</td>
<td>❌ White-list used <code>dhhdfc12p</code>; no PUMF equivalent found in either cycle</td>
</tr>
<tr class="even">
<td>Education level (4 categories)</td>
<td><code>edudh04</code></td>
<td><code>edudh04</code></td>
<td><code>education</code></td>
<td>✅ Ordered factor: Less than secondary → Post-secondary graduate. ⚠️ Cross-cycle label discrepancy for code 3 (“Other post-secondary” in 2010 vs “Some post-secondary” in 2014)</td>
</tr>
<tr class="odd">
<td>Immigration status</td>
<td><code>sdcfimm</code></td>
<td><code>sdcfimm</code></td>
<td><code>immigration_status</code></td>
<td>✅ Factor: Non-immigrant / Immigrant / Non-permanent resident</td>
</tr>
<tr class="even">
<td>Ethnic origin (White vs.&nbsp;visible minority)</td>
<td><code>sdcgcgt</code></td>
<td><code>sdcgcgt</code></td>
<td><code>visible_minority</code></td>
<td>✅ Alias <code>sdcdgcb ← sdcgcgt</code> resolves; Factor: White / Visible minority</td>
</tr>
<tr class="odd">
<td>Living arrangements</td>
<td><code>dhhglvg</code></td>
<td><code>dhhglvg</code></td>
<td><code>living_arrangements</code></td>
<td>✅ Factor (8 levels): Unattached alone / Unattached with others / Couple no children / Couple with children / Single parent / Child in parent-sibling household / Child in two-parent household / Other. <strong>Note</strong>: The Project Proposal (§2.2) specifies “homeownership” as a predisposing variable; however, no house-ownership construct exists in the CCHS PUMF. <code>living_arrangements</code> (household composition) is included as the closest available proxy, per agreement with M.-A. Blanchette (2026-05-15 review).</td>
</tr>
<tr class="even">
<td>Student status</td>
<td>❌ absent</td>
<td>❌ absent</td>
<td><code>student_status</code> (all NA)</td>
<td>❌ <code>sdcdgstud</code> not present in PUMF; column all-NA in current dataset</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="facilitating-variables" class="level2">
<h2 class="anchored" data-anchor-id="facilitating-variables">5. Facilitating Variables</h2>
<blockquote class="blockquote">
<p><em>Household income (5 categories); province/territory of residence (11 categories); having a family doctor; employment type (self-employed vs.&nbsp;employee); work schedule (full-time vs.&nbsp;part-time); occupation category; job stress level; fruit/vegetable consumption; alcohol use; smoking status; BMI/obesity category; physical activity level | Main questionnaire</em></p>
</blockquote>
<p>All 12 facilitating variables are populated in the current pipeline output. The job stress variable used is <strong>GEN_09</strong> (perceived work stress), stored as <code>work_stress</code>, not GEN_07 (life stress). Province is retained as a 13-level factor (includes the combined Yukon/NWT/Nunavut territory grouping). Employment type has <strong>2 levels</strong> in the PUMF (Employee / Self-employed); “Unpaid family worker” is not present.</p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 25%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Requested</th>
<th>2011</th>
<th>2014</th>
<th>In Study</th>
<th>Note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Household income — derived 5-category</td>
<td><code>incghh</code></td>
<td><code>incghh</code></td>
<td><code>income_hh</code></td>
<td>✅ Alias <code>incdghh ← incghh</code> resolves; Ordered factor: &lt; $20k → $80k+</td>
</tr>
<tr class="even">
<td>Province / territory of residence</td>
<td><code>geogprv</code></td>
<td><code>geogprv</code></td>
<td><code>province</code></td>
<td>✅ Alias <code>geodgprv ← geogprv</code> resolves; 13-level factor (includes NWT/Yukon/Nunavut combined)</td>
</tr>
<tr class="odd">
<td>Having a regular family doctor</td>
<td><code>hcu_1aa</code></td>
<td><code>hcu_1aa</code></td>
<td><code>has_family_doctor</code></td>
<td>✅ Factor: Yes / No</td>
</tr>
<tr class="even">
<td>Employment type (self-employed vs.&nbsp;employee)</td>
<td><code>lbsg31</code></td>
<td><code>lbsg31</code></td>
<td><code>employment_type</code></td>
<td>✅ Factor: Employee / Self-employed (2 levels in PUMF; “Unpaid family worker” suppressed)</td>
</tr>
<tr class="odd">
<td>Work schedule (full-time vs.&nbsp;part-time)</td>
<td><code>lbsdpft</code></td>
<td><code>lbsdpft</code></td>
<td><code>work_schedule</code></td>
<td>✅ Alias <code>lbfdgft ← lbsdpft</code> resolves; Factor: Full-time / Part-time</td>
</tr>
<tr class="even">
<td>Occupation category (5-group SOC)</td>
<td><code>lbsgsoc</code></td>
<td><code>lbsgsoc</code></td>
<td><code>occupation_category</code></td>
<td>✅ Factor: Mgmt/Educ/Arts / Business/Finance / Sales/Services / Trades/Transport / Primary/Processing (2010 descriptive labels applied to both cycles; codes identical)</td>
</tr>
<tr class="odd">
<td>Job / work stress level</td>
<td><code>gen_09</code></td>
<td><code>gen_09</code></td>
<td><code>work_stress</code></td>
<td>✅ GEN_09 = perceived <strong>work</strong> stress; ordered factor: Not at all / Not very / A bit / Quite a bit / Extremely stressful</td>
</tr>
<tr class="even">
<td>Total daily fruit &amp; vegetable consumption</td>
<td><code>fvcgtot</code></td>
<td><code>fvcgtot</code></td>
<td><code>fruit_veg_daily</code></td>
<td>✅ Alias <code>fvcdgtot ← fvcgtot</code> resolves; 3-category derived ordinal (&lt; 5 / 5–10 / &gt; 10 servings per day)</td>
</tr>
<tr class="odd">
<td>Alcohol use (type of drinker — derived)</td>
<td><code>alcdttm</code></td>
<td><code>alcdttm</code></td>
<td><code>alcohol_type</code></td>
<td>✅ Factor (3 levels): Former or never drinker / Occasional drinker / Regular drinker</td>
</tr>
<tr class="even">
<td>Smoking status (derived)</td>
<td><code>smkdsty</code></td>
<td><code>smkdsty</code></td>
<td><code>smoking_status</code></td>
<td>✅ Ordered factor: Never / Former / Occasional / Daily</td>
</tr>
<tr class="odd">
<td>BMI category (derived)</td>
<td><code>hwtgisw</code></td>
<td><code>hwtgisw</code></td>
<td><code>bmi_category</code></td>
<td>✅ Ordered factor: Underweight / Normal weight / Overweight / Obese</td>
</tr>
<tr class="even">
<td>Physical activity index (derived)</td>
<td><code>pacdpai</code></td>
<td><code>pacdpai</code></td>
<td><code>physical_activity</code></td>
<td>✅ Ordered factor: Active / Moderately active / Inactive</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="needs-variables" class="level2">
<h2 class="anchored" data-anchor-id="needs-variables">6. Needs Variables</h2>
<blockquote class="blockquote">
<p><em>Functional limitations (activity limitations); injury status; self-perceived general health; self-perceived mental health; self-perceived health compared to prior year | Main questionnaire</em></p>
</blockquote>
<p>Six needs variables are present. The original single-item activity limitation (<code>rac_1</code>) has been replaced by six granular ADL items with semantic names (<code>adl_meals</code>, <code>adl_errands</code>, <code>adl_housework</code>, <code>adl_personal_care</code>, <code>adl_moving_indoors</code>, <code>adl_finances</code>), each recoded to a Yes / No factor. Self-perceived mental health is captured by <code>gen_02b</code>.</p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 25%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Requested</th>
<th>2011</th>
<th>2014</th>
<th>In Study</th>
<th>Note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Functional / activity limitations — meal preparation</td>
<td><code>adl_01</code></td>
<td><code>adl_01</code></td>
<td><code>adl_meals</code></td>
<td>✅ Factor: Yes / No; semantic rename from <code>adl_01</code></td>
</tr>
<tr class="even">
<td>Functional / activity limitations — appointments / errands</td>
<td><code>adl_02</code></td>
<td><code>adl_02</code></td>
<td><code>adl_errands</code></td>
<td>✅ Factor: Yes / No; semantic rename from <code>adl_02</code></td>
</tr>
<tr class="odd">
<td>Functional / activity limitations — housework</td>
<td><code>adl_03</code></td>
<td><code>adl_03</code></td>
<td><code>adl_housework</code></td>
<td>✅ Factor: Yes / No; semantic rename from <code>adl_03</code></td>
</tr>
<tr class="even">
<td>Functional / activity limitations — personal care</td>
<td><code>adl_04</code></td>
<td><code>adl_04</code></td>
<td><code>adl_personal_care</code></td>
<td>✅ Factor: Yes / No; semantic rename from <code>adl_04</code></td>
</tr>
<tr class="odd">
<td>Functional / activity limitations — moving inside home</td>
<td><code>adl_05</code></td>
<td><code>adl_05</code></td>
<td><code>adl_moving_indoors</code></td>
<td>✅ Factor: Yes / No; semantic rename from <code>adl_05</code></td>
</tr>
<tr class="even">
<td>Functional / activity limitations — personal finances</td>
<td><code>adl_06</code></td>
<td><code>adl_06</code></td>
<td><code>adl_finances</code></td>
<td>✅ Factor: Yes / No; semantic rename from <code>adl_06</code></td>
</tr>
<tr class="odd">
<td>Injury status (past 12 months)</td>
<td><code>inj_01</code></td>
<td><code>inj_01</code></td>
<td><code>injured_past_12m</code></td>
<td>✅ Factor: Yes / No</td>
</tr>
<tr class="even">
<td>Self-perceived general health</td>
<td><code>gen_01</code></td>
<td><code>gen_01</code></td>
<td><code>health_perceived</code></td>
<td>✅ Ordered factor: Excellent → Poor</td>
</tr>
<tr class="odd">
<td>Self-perceived mental health</td>
<td><code>gen_02b</code></td>
<td><code>gen_02b</code></td>
<td><code>mental_health_perceived</code></td>
<td>✅ White-list entry <code>gen_02a</code> resolved by alias map to <code>gen_02b</code>; ordered factor: Excellent → Poor</td>
</tr>
<tr class="even">
<td>Self-perceived health compared to 1 year ago</td>
<td><code>gen_02</code></td>
<td><code>gen_02</code></td>
<td><code>health_vs_prior_year</code></td>
<td>✅ Ordered factor: Much better → Much worse; GEN_02 = health vs.&nbsp;prior year (not mental health)</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="survey-design-variables" class="level2">
<h2 class="anchored" data-anchor-id="survey-design-variables">7. Survey Design Variables</h2>
<p>These variables are retained in the analytic dataset to support complex sample survey analysis and reproducibility checks.</p>
<table class="table">
<colgroup>
<col style="width: 29%">
<col style="width: 23%">
<col style="width: 29%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Source</th>
<th>In Study</th>
<th>Note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Per-cycle sampling weight</td>
<td><code>wtsa_m</code> / <code>wts_m</code></td>
<td><code>wts_m</code></td>
<td>✅ Full-sample weight for single-cycle analysis</td>
</tr>
<tr class="even">
<td>Pooled survey weight</td>
<td>derived</td>
<td><code>wts_m_pooled</code></td>
<td>✅ Ellis-computed: <code>wts_m / 2</code> following Statistics Canada pooling guidelines</td>
</tr>
<tr class="odd">
<td>Survey cycle</td>
<td>derived</td>
<td><code>cchs_cycle_f</code></td>
<td>✅ Factor: “CCHS 2010” / “CCHS 2014”</td>
</tr>
<tr class="even">
<td>Complete CCC flag</td>
<td>derived</td>
<td><code>flag_complete_ccc</code></td>
<td>✅ Logical: TRUE if all 17 <code>cc_*</code> variables are non-missing</td>
</tr>
<tr class="odd">
<td>Complete predictors flag</td>
<td>derived</td>
<td><code>flag_complete_predictors</code></td>
<td>✅ Logical: TRUE if all predictor variables are non-missing</td>
</tr>
<tr class="even">
<td>Analytic complete flag</td>
<td>derived</td>
<td><code>flag_analytic_complete</code></td>
<td>✅ Logical: TRUE if complete CCC and complete predictors</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="coverage-summary" class="level2">
<h2 class="anchored" data-anchor-id="coverage-summary">Coverage Summary</h2>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 21%">
<col style="width: 25%">
<col style="width: 14%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>Category</th>
<th>§2.2 Requested</th>
<th>Available in PUMF</th>
<th>In Study</th>
<th>Absent / all-NA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Outcomes (primary + sensitivity)</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>0</td>
</tr>
<tr class="even">
<td>LOP components</td>
<td>8</td>
<td>8</td>
<td>8</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Chronic conditions</td>
<td>19</td>
<td>17</td>
<td>17</td>
<td>2 (RDC-only)</td>
</tr>
<tr class="even">
<td>Predisposing</td>
<td>12</td>
<td>11</td>
<td>11</td>
<td>1 (<code>dhhdfc12p</code>) + 1 all-NA (<code>student_status</code>)</td>
</tr>
<tr class="odd">
<td>Facilitating</td>
<td>12</td>
<td>12</td>
<td>12</td>
<td>0</td>
</tr>
<tr class="even">
<td>Needs</td>
<td>10</td>
<td>10</td>
<td>10</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Survey design</td>
<td>6</td>
<td>6</td>
<td>6</td>
<td>0</td>
</tr>
</tbody>
</table>
<p><strong>Total:</strong> 69 columns in <code>cchs_analytic</code>. Two chronic condition variables (<code>ccc_300</code>, <code>ccc_185</code>) and one predisposing variable (<code>dhhdfc12p</code>) require RDC access. Student status (<code>student_status</code>) is all-NA due to PUMF suppression of <code>sdcdgstud</code>.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center"><em>Absent from Chronic</em> | Marc-Andre Blanchette, Oleksandr Koval, Andriy Koval | 2026</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>